version: '3.8'

services:
  db:
    container_name: shipay-backend-challenge
    image: mysql:8.4
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
volumes:
  db_data: